# Generated by Django 5.1.6 on 2025-02-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_code",
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
